config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'

  resources :users do
  	resources :connections
	end
  
  # Now let’s return to the Callback URL. This is the URL where a user will be redirected to inside 
  # the app after successful authentication and approved authorization (the request will also contain 
  # user’s data and token). All OmniAuth strategies expect the callback URL to equal 
  # to “/auth/:provider/callback”. :provider takes the name of the strategy (“twitter”, “facebook”, 
  # “linkedin”, etc.) as listed in the initializer.

  get '/auth/:provider/callback', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord
	belongs_to :user

	has_secure_password

end

app/models/user.rb
class User < ApplicationRecord
  has_many :connections

  class << self
    def from_omniauth(auth_hash)
      user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
      user.name = auth_hash['info']['name']    
      user.location = auth_hash['info']['location'] 
      user.image_url = auth_hash['info']['image']
      user.url = auth_hash['info']['urls']['Twitter']
      user.token = auth_hash['credentials']['token']
      user.token_secret = auth_hash['credentials']['secret']
      user.save!
      user
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception



	private

	def current_user
  	@current_user ||= User.find_by(id: session[:user_id])
	end

	helper_method :current_user


end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

def create
	# unless current_user -> send to index
	user = User.find(params[:user_id])
	@connection = user.connections.new(connction_params)
	@connection.provider = current_user.provider
    if @connection.save
      puts "Success"
      flash[:success] = "Connection successfully added"
      redirect_to root_path
    else
      render 'new'
    end

end



private


def connction_params
    params.require(:connection).permit(:provider, :url, :port, :db_user, :ssl, :ssl_trust, :password,
                                   :password_confirmation, :ca_cert, :user_cert, :user_key)
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  	# if no session exists nothing gets send to the view
  	if current_user 
  		@connection = current_user.connections.new
  		@connections = current_user.connections.where("id is NOT NULL")
  	end

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    begin
      logger.info request.env['omniauth.auth']
      @user = User.from_omniauth(request.env['omniauth.auth'])
      session[:user_id] = @user.id
      flash[:success] = "Welcome, #{@user.name}!"
    rescue
      flash[:warning] = "There was an error while trying to authenticate you..."
    end
    redirect_to root_path
  end


  def destroy
  	if current_user
    	session.delete(:user_id)
    	flash[:success] = 'See you!'
  	end
  	redirect_to root_path
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twosql</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'Home', root_path, class: 'navbar-brand' %>
        </div>
        <div id="navbar">
          <% if current_user %>
            <ul class="nav navbar-nav pull-right">
              <li><%= image_tag current_user.image_url, alt: current_user.name %></li>
              <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
            </ul>
          <% else %>
            <ul class="nav navbar-nav">
              <li><%= link_to 'Twitter', '/auth/twitter' %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </nav>

	<div class="container">
  		<% flash.each do |key, value| %>
    	<div class="alert alert-<%= key %>">
      		<%= value %>
    	</div>
  		<% end %>

  		<%= yield %>
	</div>
  </body>
</html>

app/views/pages/_connection_list.html.erb
    <div class="panel panel-default">
      <div class="panel-heading">Connections ( <%= @current_user.connections.count %> )</div>
      <div class="panel-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Action</th>
              <th>Provider</th>
              <th>URL</th>
              <th>Port</th>
              <th>User</th>
              <th>Secure</th>
              <th>Trust</th>
              <th>Date Created</th>
            </tr>
          </thead>
        <tbody>
          <% @connections.each do |c| %>
            <tr>
              <td> Delete | Edit </td>
              <td><%= c.provider %> </td>
              <td><%= c.url %></td>
              <td><%= c.port %></td>
              <td><%= c.db_user %></td>
              <td><%= c.ssl %></td>
              <td><%= c.ssl_trust %></td>
              <td><%= c.created_at %> </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>

app/views/pages/_create_connection.html.erb
<%= form_for([current_user, @connection]) do |f| %>
  <!-- Modal -->
    <div class="modal fade" id="myNewConnection" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">

          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Connection</h4>
          </div>


          <div class="modal-body">

            <div class="form-inline">
              <div class="form-group">             
                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon1">URL</span>
                  <%= f.url_field :url, class: "form-control connection_url" %>
                </div>

                <div class="input-group">
                  <span class="input-group-addon" id="basic-addon1">:</span>
                  <%= f.number_field :port, class: "form-control connection_port" %>
                </div>
              </div>
            </div>

            <div class="form-group">
                <hr/>
                <h4>Database User</h4>               
                <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">User</span>
                <%= f.text_field :db_user, class: "form-control connection_db_user", placeholder: "User" %>
                </div>
            </div>
            

            <div class="form-inline">
              <div class="form-group"> 
                <div class="field">
                  <%= f.password_field :password, class: "form-control connection_password",placeholder: "Password" %>
                  <%= f.password_field :password_confirmation, class: "form-control connection_password_confirmation", placeholder: "Confirmation" %>
                </div>
              </div>
            </div>
            <div class="form-inline">
              <div class="form-group"> 
                <hr />
                <h4>Security</h4>   
                <%= f.label "ssl", "SSL" %>
                <%= f.check_box :ssl, class: "form-control connection_ssl", 'data-toggle'=> "toggle" %>

                <%= f.label "ssl_trust", "Trust" %>
                <%= f.check_box :ssl_trust, class: "form-control connection_ssl_trust", 'data-toggle'=> "toggle" %>
              </div>
            </div>

            <div class="form-group"> 
              <hr />
              <h4>Certificates</h4>
              <%= f.label "ca_cert", "CA-Certificate" %>
              <%= f.text_area :ca_cert, class: "form-control connection_ca_cert" %>

              <%= f.label "user_cert", "User-Certificate" %>
              <%= f.text_area :user_cert, class: "form-control connection_user_cert" %>

              <%= f.label "user_key", "Private Key" %>
              <%= f.text_area :user_key, class: "form-control connection_user_key" %>
            </div>

            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= submit_tag "Create", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %> 

app/views/pages/_welcome.html.erb
<div class="jumbotron">
  <h1>Welcome!</h1>
  <p>Authenticate via one of the social networks to get started.</p>
</div>

app/views/pages/index.html.erb
<% if current_user %>

<div class="container">
  <div class="row">
    <div class="page-header">
      <h1>Here is some info about you...</h1>
    </div>
  </div>

  <div class="row">

    <div class="col-sm-4 ">
      <div class="panel panel-default">
        <div class="panel-body">
          <!-- Button Trigger Modal -->
          <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myNewConnection">
            New Connection
          </button>
          <hr/>         
          <a class="twitter-timeline" href=<%=current_user.url %> >Tweets by @current_user.name</a> 
          <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

        </div>
      </div>
    </div>

    <div class="col-sm-8">
      <div class="panel panel-default">
        <div class="panel-body">
          <ul>
            <li><strong>Name:</strong> <%= current_user.name %></li>
            <li><strong>Provider:</strong> <%= current_user.provider %></li>
            <li><strong>uID:</strong> <%= current_user.uid %></li>
            <li><strong>Location:</strong> <%= current_user.location %></li>
            <li><strong>Avatar URL:</strong> <%= current_user.image_url %></li>
            <li><strong>URL:</strong> <%= current_user.url %></li>
            <li><strong>Active connections:</strong> <%= current_user.connections.count %></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-8">
      <%= render "connection_list" %>
    </div>
  </div>
  


  <!-- Create -->
  <div class="container_connections">
    <% # render @connections %>
  </div>

  <%= render "create_connection"%>





</div>
<% else %>
  <%= render 'welcome' %>
<% end %>